version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

    logging:
      options:
        max-size: 10m
        max-file: "3"
  webserver:
    image: geoscienceaustralia/airflow:0.0.4
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__SMTP__SMTP_HOST=maildev
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=False
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./scripts:/usr/local/airflow/scripts
      - ./data:/usr/local/airflow/data
      - ./requirements:/requirements
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"